name       : libmcrypt
version    : 2.5.8
release    : 2
source     :
    - https://sourceforge.net/projects/mcrypt/files/Libmcrypt/2.5.8/libmcrypt-2.5.8.tar.gz : e4eb6c074bbab168ac47b947c195ff8cef9d51a211cdd18ca9c9ef34d27a373e
license    : LGPL-2.1-or-later
component  : security.library
summary    : libmcrypt is a thread-safe library providing a uniform encryption interface.
description: |
    libmcrypt is a thread-safe library providing a uniform interface to access several block and stream encryption algorithms.
setup      : |
    # Wonder why it is like this, rather than just %configure%? Because the default configure flag uses 
    # --docdir, which is not a valid libmcrypt configure flag, so it fails with it.

    ./configure --prefix=/usr --build=x86_64-evolveos-linux --libdir=%libdir% --mandir=/usr/share/man \
        --infodir=/usr/share/man --datadir=/usr/share/ --sysconfdir=/etc --libexecdir=/usr/lib64/libmcrypt \
        --bindir=/usr/bin --disable-static
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/%libdir%/libmcrypt # Remove this empty libmcrypt dir
